"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.join(__dirname,"..");
const activation=fs.readFileSync(path.join(root,"server","modules","game-activation.js"),"utf8");
const routes=fs.readFileSync(path.join(root,"server","modules","routes.js"),"utf8");
const host=fs.readFileSync(path.join(root,"host","host.js"),"utf8");
const player=fs.readFileSync(path.join(root,"player","player.js"),"utf8");
const api=fs.readFileSync(path.join(root,"functions","api.js"),"utf8");
assert.ok(activation.includes("getOutputStatusSnapshot"));
assert.ok(activation.includes('cancelAllEventEffectRuns'),"Global Stop All must be able to cancel long-running event effects");
assert.ok(routes.includes('/api/output-status'));
assert.ok(routes.includes('/api/host/stop-all'));
assert.ok(routes.includes('const safePlayers = players.map(item => ({ id: item.id, name: item.name }))'),"Player page peer list must not expose device assignments");
assert.ok(host.includes("renderOutputStatus(data.outputStatus)"));
assert.ok(host.includes("/api/host/stop-all"));
assert.ok(player.includes("renderOutputStatus(data.outputStatus)"));
assert.ok(api.includes("setInterval(loadOutputStatus, 2500)"),"Main page status should update without a full page rerender");
console.log("Output status and Stop All regression test passed.");
