"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.join(__dirname,"..");
const setup=fs.readFileSync(path.join(root,"setup","setup.js"),"utf8");
const toySetup=fs.readFileSync(path.join(root,"intiface","setup.html"),"utf8");
const routes=fs.readFileSync(path.join(root,"server","modules","routes.js"),"utf8");
const activation=fs.readFileSync(path.join(root,"server","modules","game-activation.js"),"utf8");
assert.ok(setup.includes("/api/setup/scan-intiface"));
assert.ok(setup.includes("testPower: 25"),"Toy/Vibe setup tests need a conservative explicit base power");
assert.ok(setup.includes("testValue"),"Shock test must use an explicit test value");
assert.ok(setup.includes("window.confirm"),"Real Shock test must require deliberate confirmation");
assert.ok(setup.includes("Save assignment &amp; mapping"),"Blocked Toy guidance must explain how to persist assignment and mapping");
assert.ok(toySetup.includes("Save assignment &amp; mapping"),"Toy Setup must expose an explicit assignment-and-mapping save action");
assert.ok(setup.includes("Toy assignment saved"),"Player Setup must confirm that Toy assignment is persisted immediately");
assert.ok(setup.includes("Toy gameplay is disabled"),"Player Setup must explain when Toy gameplay integration is disabled");
const setupHtml=fs.readFileSync(path.join(root,"setup","index.html"),"utf8");
assert.ok(setupHtml.includes('id="toyIntegrationNotice"'),"Setup must provide a dedicated Toy integration warning area");
assert.ok(setupHtml.includes('href="#intiface"'),"Setup must expose basic Toy settings without editing config files");
assert.ok(setupHtml.includes('id="intifaceEnabled"'),"Setup Toy settings must control the Intiface connection flag");
assert.ok(setupHtml.includes('id="intifaceWebsocketUrl"'),"Setup Toy settings must control the Intiface WebSocket URL");
assert.ok(setupHtml.includes('id="intifaceGameIntegrationEnabled"'),"Setup Toy settings must control gameplay integration");
assert.ok(setupHtml.includes('id="saveIntifaceSettingsBtn"'),"Setup Toy settings must provide an explicit save button");
const intifaceClient=fs.readFileSync(path.join(root,"intiface","intiface-client.js"),"utf8");
assert.ok(intifaceClient.includes("Disconnected — mapping can still be saved"),"A disconnected Toy must retain its mapping card so the profile can be saved");
assert.ok(intifaceClient.includes("Automatic mapping save failed"),"Toy mapping changes must be persisted automatically");
assert.ok(routes.includes('/api/setup/test-device'));
assert.ok(routes.includes('/api/setup/stop-device'));
const playerSetup=fs.readFileSync(path.join(root,"server","modules","player-setup.js"),"utf8");
assert.ok(playerSetup.includes("updateIntifaceSettings"),"Player Setup must be able to save basic Intiface settings");
assert.ok(playerSetup.includes("setupIntifaceConfigSnapshot"),"Player Setup state must expose safe Intiface settings to the setup UI");
assert.ok(playerSetup.includes("writeConfig(next)"),"Player Setup Intiface settings must persist to config");
assert.ok(setup.includes("/api/intiface/connect"),"Setup Toy settings must be able to connect to Intiface");
assert.ok(setup.includes("/api/intiface/reconnect"),"Setup Toy settings must be able to reconnect Intiface");
assert.ok(setup.includes("/api/intiface/disconnect"),"Setup Toy settings must be able to disconnect Intiface");
assert.ok(activation.includes("requireGameIntegration = true"),"Setup tests must be able to reuse Toy templates while gameplay integration is disabled");
assert.ok(activation.includes("durationMsOverride"),"Setup Toy tests need a bounded direct duration");
assert.ok(activation.includes("Device multiplier is 0%"),"0% profiles must stay silent during tests");
console.log("Player Setup device control regression test passed.");
