"use strict";
let state = null;
let templates = [];
const $ = id => document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function statusText(ok,text,disabled=false){return `<span class="${disabled?'status-disabled':ok?'status-ok':'status-bad'}">● ${esc(text)}</span>`;}
async function api(action){const res=await fetch('/api/setup/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Setup action failed');state=data;render();return data;}
async function load(refresh=false){const [stateRes,templateRes]=await Promise.all([fetch(`/api/setup/state${refresh?'?refresh=1':''}`,{cache:'no-store'}),fetch('/api/intiface/templates',{cache:'no-store'})]);const data=await stateRes.json();if(!stateRes.ok)throw new Error(data.error||'Could not load setup');state=data;if(templateRes.ok){const t=await templateRes.json();templates=Array.isArray(t.templates)?t.templates:templates;}render();}
function deviceLabel(d){return `${d.provider==='intiface'?'Toy':'Shock'} · ${esc(d.memberName||d.name)}${d.online===false?' · offline':''}`;}
function templateOptions(selected){const list=templates.length?templates:[{id:'soft-wave',name:'Soft wave'}];return list.map(t=>`<option value="${esc(t.id)}"${String(t.id)===String(selected)?' selected':''}>${esc(t.name||t.id)}</option>`).join('');}
function playerCard(p){const devices=(p.devices||[]).map(d=>`<div class="device-row"><div><strong>${deviceLabel(d)}</strong><div class="device-meta">${d.enabled===false?'disabled':'enabled'} · ${esc(d.intensityMultiplier??100)}%</div></div><div class="device-actions"><label><input type="checkbox" data-device-enabled data-provider="${esc(d.provider)}" data-device="${esc(d.id)}"${d.enabled!==false?' checked':''}> Enabled</label><label>Multiplier <input class="device-percent" type="number" min="0" max="100" step="1" value="${esc(d.intensityMultiplier??100)}" data-device-multiplier data-provider="${esc(d.provider)}" data-device="${esc(d.id)}">%</label>${d.provider==='intiface'?`<label>Template <select data-device-template data-provider="intiface" data-device="${esc(d.id)}">${templateOptions(d.preferredTemplate||'soft-wave')}</select></label>`:''}<button data-action="unassign" data-provider="${esc(d.provider)}" data-device="${esc(d.id)}">Unassign</button></div></div>`).join('')||'<p class="device-meta">No devices assigned.</p>';return `<div class="player-card"><div class="player-card-head"><div><strong>${esc(p.name)}</strong><div class="device-meta">${esc(p.id)}</div></div><div><button data-action="rename" data-player="${esc(p.id)}">Rename</button> <button data-action="toggle" data-player="${esc(p.id)}" data-enabled="${p.enabled!==false}">${p.enabled===false?'Enable':'Disable'}</button> <button data-action="remove" data-player="${esc(p.id)}">Remove</button></div></div>${devices}</div>`;}
function pool(items,provider){const unassigned=(items||[]).filter(d=>!d.assigned);if(!unassigned.length)return '<p class="device-meta">None.</p>';const options=(state.players||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');return unassigned.map(d=>`<div class="device-row"><div><strong>${esc(d.name)}</strong><div class="device-meta">${d.online===false?'offline':'online'}</div></div><div><select data-assign-player="${esc(provider)}:${esc(d.id)}"><option value="">Assign to…</option>${options}</select></div></div>`).join('');}
function render(){if(!state)return;$('shockStatus').innerHTML=statusText(Boolean(state.providers?.shock?.reachable),state.providers?.shock?.reachable?'reachable':'last request failed');const toy=state.providers?.toy||{};$('toyStatus').innerHTML=statusText(Boolean(toy.connected),toy.enabled===false?'disabled':toy.connected?'connected':'disconnected',toy.enabled===false);const ready=(state.readiness||[]).filter(r=>r.enabled&&r.ready).length;const active=(state.readiness||[]).filter(r=>r.enabled).length;$('readiness').textContent=`Ready ${ready}/${active} active players`;$('players').innerHTML=(state.players||[]).map(playerCard).join('')||'<p>No players yet.</p>';$('shockDevices').innerHTML=pool(state.devices?.shock,'openshock');$('toyDevices').innerHTML=pool(state.devices?.toy,'intiface');$('suggestions').innerHTML=(state.suggestions||[]).map(s=>`<div class="device-row"><span>${esc(s.deviceName)} → <strong>${esc(s.playerName)}</strong></span><button data-action="accept-suggestion" data-provider="${esc(s.provider)}" data-device="${esc(s.deviceId)}" data-name="${esc(s.deviceName)}" data-player="${esc(s.playerId)}">Accept</button></div>`).join('')||'<p class="device-meta">No suggestions.</p>';bindDynamic();}
function updateDevice(provider,deviceId,patch){return api({action:'updateDevice',provider,deviceId,...patch});}
function bindDynamic(){document.querySelectorAll('[data-assign-player]').forEach(sel=>sel.onchange=()=>{if(!sel.value)return;const [provider,...rest]=sel.dataset.assignPlayer.split(':');api({action:'assignDevice',provider,deviceId:rest.join(':'),playerId:sel.value,deviceName:sel.closest('.device-row').querySelector('strong').textContent}).catch(showError);});document.querySelectorAll('[data-device-enabled]').forEach(el=>el.onchange=()=>updateDevice(el.dataset.provider,el.dataset.device,{enabled:el.checked}).catch(showError));document.querySelectorAll('[data-device-multiplier]').forEach(el=>el.onchange=()=>updateDevice(el.dataset.provider,el.dataset.device,{intensityMultiplier:Math.max(0,Math.min(100,Number(el.value)||0))}).catch(showError));document.querySelectorAll('[data-device-template]').forEach(el=>el.onchange=()=>updateDevice(el.dataset.provider,el.dataset.device,{preferredTemplate:el.value}).catch(showError));document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=async()=>{try{const a=btn.dataset.action;if(a==='unassign')await api({action:'unassignDevice',provider:btn.dataset.provider,deviceId:btn.dataset.device});if(a==='remove'&&confirm('Remove this player? Devices will become unassigned.'))await api({action:'removePlayer',playerId:btn.dataset.player});if(a==='toggle')await api({action:'setPlayerEnabled',playerId:btn.dataset.player,enabled:btn.dataset.enabled!=='true'});if(a==='rename'){const name=prompt('Player name');if(name)await api({action:'renamePlayer',playerId:btn.dataset.player,name});}if(a==='accept-suggestion')await api({action:'assignDevice',provider:btn.dataset.provider,deviceId:btn.dataset.device,deviceName:btn.dataset.name,playerId:btn.dataset.player});}catch(e){showError(e);}});}
function showError(err){$('message').textContent=err.message||String(err);}
$('createPlayerBtn').onclick=()=>{const name=$('newPlayerName').value.trim();if(!name)return;api({action:'createPlayer',name}).then(()=>{$('newPlayerName').value='';}).catch(showError);};$('refreshBtn').onclick=()=>load(true).catch(showError);load().catch(showError);
